# Generated by Django 4.2.3 on 2023-09-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
