# Generated by Django 4.2.3 on 2023-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ownership_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='last_received',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
