# Generated by Django 4.2.3 on 2024-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_ownership_last_received_distribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=2000)),
                ("image_url", models.CharField(max_length=2000, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("IMAGE", "Image Choice"), ("TEXT", "Text Choice")],
                        default="IMAGE",
                        max_length=5,
                    ),
                ),
                ("answers", models.ManyToManyField(to="core.quizanswer")),
            ],
        ),
    ]
