# Generated by Django 4.2.3 on 2024-02-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_ownership_last_received_distribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_received_unique",
            field=models.DateTimeField(null=True),
        ),
    ]
