# Generated by Django 4.2.3 on 2024-02-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_quizanswer_quizquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="correct_answer_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
