# Generated by Django 4.2.3 on 2024-02-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_last_received_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=2000)),
                ("question_timestamp", models.DateTimeField(auto_now_add=True)),
                ("image_url", models.CharField(max_length=2000, null=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[("IMAGE", "Image question")],
                        default="IMAGE",
                        max_length=5,
                    ),
                ),
                (
                    "answer_type",
                    models.CharField(
                        choices=[("NAME", "Name answer"), ("ENTRY", "Beitritt answer")],
                        default="NAME",
                        max_length=5,
                    ),
                ),
                ("answer_timestamp", models.DateTimeField(null=True)),
                ("answers", models.ManyToManyField(to="core.quizanswer")),
                (
                    "correct_answer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="correct_answer",
                        to="core.quizanswer",
                    ),
                ),
                (
                    "given_answer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="given_answer",
                        to="core.quizanswer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.user"
                    ),
                ),
            ],
        ),
    ]
