# Generated by Django 4.2.3 on 2023-09-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ownership_last_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='password',
        ),
    ]
