# Generated by Django 4.2.3 on 2023-09-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_otp_otp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='otp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.otp'),
        ),
    ]
