# Generated by Django 4.2.3 on 2024-03-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quizanswer_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_timestamp', models.DateTimeField(auto_now_add=True)),
                ('question_type', models.CharField(choices=[('IMAGE', 'Image'), ('NAME', 'Name'), ('POSITION', 'Position'), ('ACRONYM', 'Acronym'), ('WISH_DESTINATION', 'Wish Destination'), ('WISH_PERSON', 'Wish Person'), ('WISH_SKILL', 'Wish Skill'), ('BEST_ADVICE', 'Best Advice')], default='IMAGE', max_length=16)),
                ('answer_type', models.CharField(choices=[('IMAGE', 'Image'), ('NAME', 'Name'), ('POSITION', 'Position'), ('ACRONYM', 'Acronym'), ('WISH_DESTINATION', 'Wish Destination'), ('WISH_PERSON', 'Wish Person'), ('WISH_SKILL', 'Wish Skill'), ('BEST_ADVICE', 'Best Advice')], default='NAME', max_length=16)),
                ('answer_timestamp', models.DateTimeField(null=True)),
                ('question_answer_card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='answer_card', to='core.card')),
                ('question_true_card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='true_card', to='core.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='given_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
