# Generated by Django 4.2.3 on 2024-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_quizquestion_correct_answer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="correct_answer_id",
            field=models.IntegerField(null=True),
        ),
    ]
