# Generated by Django 4.2.3 on 2023-09-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ownership_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='otp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.otp', unique=True),
        ),
    ]
