# Generated by Django 4.2.3 on 2024-03-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quiz_remove_quizquestion_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_answer_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='answer_card', to='core.card'),
        ),
    ]
