# Generated by Django 4.2.3 on 2024-02-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_quizquestion_correct_answer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="correct_answer_id",
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="correct_answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="correct_answer",
                to="core.quizanswer",
            ),
        ),
    ]
