# Generated by Django 4.2.3 on 2023-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ownership_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='otp',
        ),
        migrations.AddField(
            model_name='ownership',
            name='otp_valid_to',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ownership',
            name='otp_value',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
