# Generated by Django 4.2.3 on 2024-02-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_quizquestion_correct_answer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="given_answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="given_answer",
                to="core.quizanswer",
            ),
        ),
    ]
