# Generated by Django 4.2.3 on 2024-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_quizquestion_given_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="answer_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
