# Generated by Django 4.2.3 on 2024-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_quiz_answer_type_alter_quiz_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question_answer_card',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_options',
            field=models.IntegerField(null=True),
        ),
    ]
