# Generated by Django 4.2.3 on 2024-02-23 12:55

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_quizquestion_answer_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="question_timestamp",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.RESTRICT, to="core.user"
            ),
            preserve_default=False,
        ),
    ]
