# Generated by Django 4.2.3 on 2024-02-23 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_last_received_unique"),
        ("core", "0009_quizquestion_question_timestamp_quizquestion_user"),
    ]

    operations = []
