# Generated by Django 4.2.3 on 2023-09-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ownership_otp_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='otp_value',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
