# Generated by Django 4.2.3 on 2024-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_merge_20240223_1322"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="type",
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="answer_type",
            field=models.CharField(
                choices=[("NAME", "Name answer")], default="NAME", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[("IMAGE", "Image question")], default="IMAGE", max_length=5
            ),
        ),
    ]
