# Generated by Django 4.2.3 on 2024-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_quizquestion_type_quizquestion_answer_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="answer_type",
            field=models.CharField(
                choices=[("NAME", "Name answer"), ("ENTRY", "Beitritt answer")],
                default="NAME",
                max_length=5,
            ),
        ),
    ]
